name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alexxlalex/yashka:latest
    steps:
      - name: clone
        uses: actions/checkout@v1
      - name: add build folder
        run: mkdir -p build
      - name: build
        working-directory: ./build
        run: cmake -S .. -B . && cmake --build .
      - name: tests
        working-directory: ./build/tests
        run: ctest
      - name: run lint
        run: cmake --build ./build --target cpplint
      - name: show lint analyze
        run: echo "$(cat lint/analyze.txt)"