name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alexxlalex/yashka:latest
    steps:
      - name: clone
        uses: actions/checkout@v1
      - name: build
        working-directory: ./build
        run: cmake -S .. -B . && cmake --build .
      - name: tests
        working-directory: ./build/tests
        run: ctest
      - name: run lint
        continue-on-error: true
        run: cmake --build ./build --target cpplint && exit 0
      - name: show lint analyze
        run: echo "$(cat lint/analyze.txt)"